spring:
  data:
    mongodb:
      host: 127.0.0.1
      database: test
      port: 27017
#打印Mongodb语句
logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core: DEBUG
server:
  port: 9001


